# Generated by Django 4.0 on 2022-01-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.CharField(blank=True, max_length=200, verbose_name='preview'),
        ),
    ]
