# Generated by Django 4.0 on 2022-01-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0002_article_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
