# Generated by Django 4.0 on 2022-01-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0003_article_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='capture',
            field=models.CharField(blank=True, choices=[('want', 'want'), ('already', 'already')], max_length=20, verbose_name='capture'),
        ),
    ]
