# Generated by Django 4.0 on 2022-01-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0004_category_capture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='capture',
            field=models.CharField(choices=[('want', 'want'), ('already', 'already')], max_length=20, verbose_name='capture'),
        ),
    ]
