# Generated by Django 4.0 on 2022-01-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0005_alter_category_capture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='capture',
            new_name='chapter',
        ),
    ]
