# Generated by Django 4.0 on 2022-01-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0006_rename_capture_category_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=9999, verbose_name='article text'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph10',
            field=models.TextField(blank=True, max_length=9999, verbose_name='article text'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=9999, verbose_name='article text'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=9999, verbose_name='article text'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph4',
            field=models.TextField(blank=True, max_length=9999, verbose_name='article text'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph5',
            field=models.TextField(blank=True, max_length=9999, verbose_name='article text'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph6',
            field=models.TextField(blank=True, max_length=9999, verbose_name='article text'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph7',
            field=models.TextField(blank=True, max_length=9999, verbose_name='article text'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph8',
            field=models.TextField(blank=True, max_length=9999, verbose_name='article text'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph9',
            field=models.TextField(blank=True, max_length=9999, verbose_name='article text'),
        ),
    ]
