# Generated by Django 4.0 on 2022-01-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0007_remove_article_preview_remove_article_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.TextField(blank=True, max_length=200, verbose_name='preview'),
        ),
    ]
