# Generated by Django 4.0 on 2022-01-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0008_article_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
