# Generated by Django 4.0 on 2022-01-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0010_messages_alter_reviews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
