# Generated by Django 4.0 on 2022-01-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0011_messages_email_reviews_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
