# Generated by Django 4.0 on 2022-01-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0012_alter_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
