# Generated by Django 4.0 on 2022-01-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0013_alter_reviews_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
