# Generated by Django 4.0 on 2022-01-01 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0014_alter_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
