# Generated by Django 4.0 on 2022-01-01 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0015_reviews_time_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
