# Generated by Django 4.0 on 2022-01-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0016_alter_reviews_date_alter_reviews_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
