# Generated by Django 4.0 on 2022-01-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0017_alter_reviews_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('-time',), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='title',
        ),
    ]
