# Generated by Django 4.0 on 2022-01-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0019_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
