# Generated by Django 4.0 on 2022-01-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0020_category_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Surname'),
        ),
    ]
