# Generated by Django 4.0 on 2022-01-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0021_alter_contact_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
