# Generated by Django 4.0 on 2022-01-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0027_remove_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='advises',
            name='advise',
            field=models.TextField(blank=True, max_length=9999, null=True, verbose_name='advise'),
        ),
    ]
