# Generated by Django 4.0 on 2022-01-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0029_alter_advises_options_remove_advises_advise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='advise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_docs.advises', verbose_name='advise'),
        ),
    ]
