# Generated by Django 4.0 on 2022-01-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0030_article_advise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(verbose_name='Phone'),
        ),
    ]
