# Generated by Django 4.0 on 2022-01-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs', '0033_servicecategory_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_name_ua',
            field=models.CharField(blank=True, max_length=50, verbose_name='service name ua'),
        ),
    ]
