# Generated by Django 4.0 on 2022-01-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryUa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('chapter', models.CharField(choices=[('want', 'want'), ('already', 'already')], max_length=20, verbose_name='capture')),
                ('place', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Surname')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='MessagesUA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('auth', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ReviewsUa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('auth', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='ArticleUa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('preview', models.TextField(blank=True, max_length=200, verbose_name='preview')),
                ('paragraph1', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph2', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph3', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph4', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph5', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph6', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph7', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph8', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph9', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph10', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web_docs_ua.categoryua', verbose_name='category')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
