# Generated by Django 4.0 on 2022-01-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs_ua', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUa',
        ),
        migrations.DeleteModel(
            name='MessagesUA',
        ),
        migrations.DeleteModel(
            name='ReviewsUa',
        ),
    ]
