# Generated by Django 4.0 on 2022-01-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs_ua', '0002_delete_contactua_delete_messagesua_delete_reviewsua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('preview', models.TextField(blank=True, max_length=200, verbose_name='preview')),
                ('paragraph1', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph2', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph3', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph4', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph5', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph6', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph7', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph8', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph9', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('paragraph10', models.TextField(blank=True, max_length=9999, verbose_name='article text')),
                ('date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
