# Generated by Django 4.0 on 2022-01-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs_ua', '0003_advises'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advises',
            new_name='AdvisesUa',
        ),
    ]
