# Generated by Django 4.0 on 2022-01-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs_ua', '0005_articleua_advise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisesua',
            name='date',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='paragraph1',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='paragraph10',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='paragraph2',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='paragraph3',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='paragraph4',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='paragraph5',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='paragraph6',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='paragraph7',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='paragraph8',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='paragraph9',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='title',
        ),
        migrations.RemoveField(
            model_name='advisesua',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='articleua',
            name='advise',
        ),
        migrations.AddField(
            model_name='advisesua',
            name='text',
            field=models.TextField(max_length=9999, null=True, verbose_name='advise text'),
        ),
        migrations.AlterField(
            model_name='advisesua',
            name='preview',
            field=models.TextField(max_length=200, verbose_name='preview'),
        ),
    ]
