# Generated by Django 4.0 on 2022-01-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs_ua', '0006_remove_advisesua_date_remove_advisesua_paragraph1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleua',
            name='advise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_docs_ua.advisesua', verbose_name='advise'),
        ),
    ]
