# Generated by Django 4.0 on 2022-01-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_docs_ua', '0008_servicecategoryua_servicesua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesua',
            name='category',
        ),
        migrations.DeleteModel(
            name='ServiceCategoryUa',
        ),
        migrations.DeleteModel(
            name='ServicesUa',
        ),
    ]
